M48
; DRILL file {KiCad 9.0.1} date 2025-09-21T13:47:28+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-21T13:47:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.270
%
G90
G05
T1
X57.3Y-135.575
X61.7Y-135.575
T2
X75.0Y-138.0
X84.0Y-138.0
M30
